# Import packages

In [1]:
import numpy as np

# Create Sigmoid Function and derivative of sigmoid

In [2]:
def sigmoid(x,derivative):
    if derivative== False:
        return 1/(1+np.exp(-x))
    if derivative==True:
        return x*(1-x)
    

# Generating Sample Data

In [3]:
x=np.array([[0,1,0],[1,0,0],[1,1,0],[0,1,1]])
y=np.array([0,0,1,1])

# Generating the weights

In [73]:
np.random.random((3,1))

array([[0.34634715],
       [0.04309736],
       [0.87991517]])

In [4]:
# Initialize the weight between -1 to 1
np.random.seed(10)
weights=2*np.random.random((3,1))-1
weights

array([[ 0.54264129],
       [-0.9584961 ],
       [ 0.26729647]])

In [5]:
for i in range(2):
    input_layer=x
    # Multiply the input with weight
    outputs = sigmoid(np.dot(input_layer,weights), derivative=False)
    
    # Error
    error=y-outputs

# Neural Network Class

In [6]:
def weight_bais_int(layers,units):
    w=[]
    b=[]
    for i in range(layers):
     
        try:
            w.append(np.random.randn(units[i],units[i+1]))
            b.append(np.random.randn(1))
        except:
            break
    w.append(np.random.randn(units[len(units)-1]))
    b.append(np.random.randn(1))
    return w,b
            
    

In [7]:
w,b=weight_bais_int(layers=3,units=[3,4,2,1])

In [8]:
w

[array([[-0.01002595,  1.67080819, -0.66437971, -0.60555494],
        [-0.65099088,  0.51256776,  0.26238882, -0.58273165],
        [ 1.36842193,  0.05336866,  1.49057364,  0.75636693]]),
 array([[-0.23396259,  0.35365794],
        [ 1.78370094, -0.35030121],
        [-0.9896496 , -0.63425417],
        [ 1.89876222,  1.99652279]]),
 array([[2.18032831],
        [0.19046688]]),
 array([0.41765968])]

In [9]:
def forward_values(x,w,b):
    z_values=[]
    z=x
    #z_values.append(z)
    for i in range(len(w)):
        z=np.dot(z,w[i])
        z=sigmoid(z,derivative=False)
        z_values.append(z)
    return z_values
        

In [10]:
z_values=forward_values(x,w,b)

In [11]:
z_values

[array([[0.34276628, 0.62540822, 0.56522343, 0.35830428],
        [0.49749353, 0.84168354, 0.33975646, 0.35307384],
        [0.34051123, 0.8987467 , 0.4008341 , 0.23356552],
        [0.67204107, 0.637825  , 0.85232607, 0.54330009]]),
 array([[0.76066126, 0.56439245],
        [0.84801033, 0.59158651],
        [0.82781618, 0.50442004],
        [0.76288284, 0.63607332]]),
 array([[0.8539582 ],
        [0.87670801],
        [0.87000312],
        [0.85624991]]),
 array([0.58823262, 0.59053213, 0.58985482, 0.58846444])]

In [12]:
def rmse_error(z_values,y):
    e=np.mean((y-z_values[len(z_values)-1])*2)
    er=np.sqrt(e)
    return er

In [13]:
def backward_values(x,y,z_values,w):
    delta=[]
    out_error=z_values[len(z_values)-1]-y
    d=out_error*sigmoid(z_values[len(z_values)-1],derivative=True)
    delta.append(d)
    
    for i in range(len(z_values)):
        e=d.dot(w[i].T)
    
    

    

In [14]:
out_error=z_values[len(z_values)-1]-y

In [15]:
sigmoid(z_values[len(z_values)-1],derivative=True)*out_error

array([ 0.14247877,  0.14279299, -0.09922483, -0.09966323])

In [16]:
delta=[]
out_error=z_values[len(z_values)-1]-y
d=out_error*sigmoid(z_values[len(z_values)-1],derivative=True)
delta.append(d)



In [17]:
l=len(z_values)-1

In [18]:
d

array([ 0.14247877,  0.14279299, -0.09922483, -0.09966323])

In [19]:
for i in range(len(z_values)-1):
    e=d.dot(w[i].T)+b[i]
    d=e*sigmoid(z_values[i],derivative=True)
    delta.append(d)

ValueError: operands could not be broadcast together with shapes (3,) (4,4) 

In [20]:
e

array([0.83306666, 0.48212106, 0.44894878])

In [217]:
sigmoid(z_values[i],derivative=True)

array([[0.24511435, 0.24736082, 0.13337589, 0.18953119],
       [0.24408337, 0.17409511, 0.22921704, 0.23837408],
       [0.2499485 , 0.15429226, 0.1896162 , 0.14772183],
       [0.22998914, 0.24457405, 0.23049612, 0.06446784]])

In [30]:
w[-5]

IndexError: list index out of range

In [33]:
size=[3,4,2,1]

In [34]:
 deltas = [0] * (len(size) - 1)

In [35]:
deltas

[0, 0, 0]

In [36]:

weights = [np.random.randn(size[i], size[i-1]) * np.sqrt(1 / size[i-1]) for i in range(1, len(size))]

In [38]:
biases = [np.random.rand(n, 1) for n in size[1:]]

In [41]:
biases

[array([[0.90283176],
        [0.53455795],
        [0.59020136],
        [0.03928177]]), array([[0.35718176],
        [0.07961309]]), array([[0.30545992]])]

In [57]:
np.dot(weights[0],weights[1])

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

In [111]:
weights[1].shape

(2, 4)

In [49]:
weights[0]

array([[ 0.02734052, -0.35127464, -0.15504634],
       [-0.38468962, -0.19861532,  0.46595164],
       [ 1.23657192, -0.28614529,  0.30347691],
       [-0.2249625 ,  0.54114838, -0.47168027]])

In [61]:
delta

[array([ 0.14247877,  0.14279299, -0.09922483, -0.09966323])]

In [64]:
delta=[0]*(len(size)-1)

In [65]:
delta

[0, 0, 0]

In [66]:
for i in range(len(delta)-2,-1,-1):
    print(i)

1
0


In [70]:
[1]+delta

[1, 0, 0, 0]

In [74]:
# Test

In [75]:
def activation(z, derivative=False):
    """
    Sigmoid activation function:
    It handles two modes: normal and derivative mode.
    Applies a pointwize operation on vectors
    
    Parameters:
    ---
    z: pre-activation vector at layer l
        shape (n[l], batch_size)
    Returns: 
    pontwize activation on each element of the input z
    """
    if derivative:
        return activation(z) * (1 - activation(z))
    else:
        return 1 / (1 + np.exp(-z))

def cost_function(y_true, y_pred):
    """
    Computes the Mean Square Error between a ground truth vector and a prediction vector
    Parameters:
    ---
    y_true: ground-truth vector
    y_pred: prediction vector
    Returns:
    ---
    cost: a scalar value representing the loss
    """
    n = y_pred.shape[1]
    cost = (1./(2*n)) * np.sum((y_true - y_pred) ** 2)
    return cost

def cost_function_prime(y_true, y_pred):
    """
    Computes the derivative of the loss function w.r.t the activation of the output layer
    Parameters:
    ---
    y_true: ground-truth vector
    y_pred: prediction vector
    Returns:
    ---
    cost_prime: derivative of the loss w.r.t. the activation of the output
    shape: (n[L], batch_size)    
    """
    cost_prime = y_pred - y_true
    return cost_prime

In [79]:
layers=[3,4,2,1]

In [97]:
def weigh_int(layers):
    weights = [np.random.randn(layers[i], layers[i-1]) * np.sqrt(1 / layers[i-1]) for i in range(1, len(layers))]
    biases = [np.random.rand(n, 1) for n in layers[1:]]
    return weights,biases
weights,biases=weigh_int(layers)

In [114]:
def forward( x,weights, biases):
    '''
    Perform a feed forward computation 
    Parameters
    ---
    input: data to be fed to the network with
    shape: (input_shape, batch_size)
    Returns
    ---
    a: ouptut activation (output_shape, batch_size)
    pre_activations: list of pre-activations per layer
    each of shape (n[l], batch_size), where n[l] is the number 
    of neuron at layer l
    activations: list of activations per layer
    each of shape (n[l], batch_size), where n[l] is the number 
    of neuron at layer l
    '''
    a = x
    pre_activations = []
    activations = [a]
    for w, b in zip(weights, biases):
        z = np.dot(a,w) + b
        a  = activation(z)
        pre_activations.append(z)
        activations.append(a)
    return a, pre_activations, activations

In [115]:
weights[2].shape

(1, 2)

In [117]:
forward( x,weights, biases)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [1]:
import numpy as np

In [27]:
a=np.array([i*2 for i in range(10)])
b=np.array([i*3 for i in range(20)])

In [28]:
a=a.reshape(5,2)
b=b.reshape(-1,2)

In [30]:
np.dot(a,b.T)

array([[   6,   18,   30,   42,   54,   66,   78,   90,  102,  114],
       [  18,   78,  138,  198,  258,  318,  378,  438,  498,  558],
       [  30,  138,  246,  354,  462,  570,  678,  786,  894, 1002],
       [  42,  198,  354,  510,  666,  822,  978, 1134, 1290, 1446],
       [  54,  258,  462,  666,  870, 1074, 1278, 1482, 1686, 1890]])

In [33]:
b.T.shape

(2, 10)