# Import packages

In [1]:
import numpy as np

# Create Sigmoid Function and derivative of sigmoid

In [58]:
def sigmoid(x,derivative):
    if derivative== False:
        return 1/(1+np.exp(-x))
    if derivative==True:
        return x*(1-x)
    

# Generating Sample Data

In [3]:
x=np.array([[0,1,0],[1,0,0],[1,1,0],[0,1,1]])
y=np.array([0,0,1,1])

# Generating the weights

In [4]:
# Initialize the weight between -1 to 1
np.random.seed(10)
weights=2*np.random.random((3,1))-1
weights

array([[ 0.54264129],
       [-0.9584961 ],
       [ 0.26729647]])

In [6]:
for i in range(2):
    input_layer=x
    # Multiply the input with weight
    outputs = sigmoid(np.dot(input_layer,weights), derivative=False)
    
    # Error
    error=y-outputs

# Neural Network Class

In [42]:
def weight_bais_int(layers,units):
    w=[]
    b=[]
    for i in range(layers):
     
        try:
            w.append(np.random.randn(units[i],units[i+1]))
            b.append(np.random.randn(1))
        except:
            break
    w.append(np.random.randn(units[len(units)-1]))
    b.append(np.random.randn(1))
    return w,b
            
    

In [43]:
w,b=weight_bais_int(layers=3,units=[3,4,2,1])

In [72]:
w

[array([[-0.31014077, -1.2396806 , -0.59347881, -0.43817284],
        [ 0.28143276, -0.20621966,  1.66945183, -1.07688513],
        [ 0.3002728 ,  0.50302378, -1.09557915, -1.52114107]]),
 array([[ 0.69714806, -0.19580128],
        [ 0.11989141,  0.76399539],
        [-0.33265382,  0.02295053],
        [ 0.0554339 ,  0.36275798]]),
 array([[1.40695393],
        [0.22088226]]),
 array([-0.77140026])]

In [212]:
def forward_values(x,w,b):
    z_values=[]
    z=x
    #z_values.append(z)
    for i in range(len(w)):
        z=np.dot(z,w[i])
        z=sigmoid(z,derivative=False)
        z_values.append(z)
    return z_values
        

In [213]:
z_values=forward_values(x,w,b)

In [76]:
z_values

[array([[0.56989745, 0.44862702, 0.84150272, 0.25409593],
        [0.42308038, 0.22449159, 0.35583705, 0.39217643],
        [0.49282349, 0.19063332, 0.74573116, 0.18019041],
        [0.64145976, 0.57366107, 0.63965629, 0.06926556]]),
 array([[0.54617948, 0.58483424],
        [0.55607155, 0.5594925 ],
        [0.53204217, 0.53285956],
        [0.57615893, 0.58721954]]),
 array([[0.71046199],
        [0.71217049],
        [0.70396648],
        [0.71916741]]),
 array([0.36631681, 0.36601093, 0.3674807 , 0.36475939])]

In [49]:
def rmse_error(z_values,y):
    e=np.mean((y-z_values[len(z_values)-1])*2)
    er=np.sqrt(e)
    return er

In [145]:
def backward_values(x,y,z_values,w):
    delta=[]
    out_error=z_values[len(z_values)-1]-y
    d=out_error*sigmoid(z_values[len(z_values)-1],derivative=True)
    delta.append(d)
    
    for i in range(len(z_values)):
        e=d.dot(w[i].T)
    
    

    

In [153]:
out_error=z_values[len(z_values)-1]-y

In [156]:
sigmoid(z_values[len(z_values)-1],derivative=True)*out_error

array([ 0.08503268,  0.08493171, -0.14702192, -0.14719159])

In [205]:
delta=[]
out_error=z_values[len(z_values)-1]-y
d=out_error*sigmoid(z_values[len(z_values)-1],derivative=True)
delta.append(d)



In [158]:
l=len(z_values)-1

In [186]:
d

array([ 0.08503268,  0.08493171, -0.14702192, -0.14719159])

In [208]:
for i in range(len(z_values)-1):
    e=d.dot(w[i].T)+b[i]
    d=e*sigmoid(z_values[i],derivative=True)
    delta.append(d)

ValueError: operands could not be broadcast together with shapes (3,) (4,4) 

In [216]:
e

array([0.25619136, 0.15558072, 0.68933091])

In [217]:
sigmoid(z_values[i],derivative=True)

array([[0.24511435, 0.24736082, 0.13337589, 0.18953119],
       [0.24408337, 0.17409511, 0.22921704, 0.23837408],
       [0.2499485 , 0.15429226, 0.1896162 , 0.14772183],
       [0.22998914, 0.24457405, 0.23049612, 0.06446784]])

In [214]:
z_values[0]

array([[0.56989745, 0.44862702, 0.84150272, 0.25409593],
       [0.42308038, 0.22449159, 0.35583705, 0.39217643],
       [0.49282349, 0.19063332, 0.74573116, 0.18019041],
       [0.64145976, 0.57366107, 0.63965629, 0.06926556]])

In [203]:
w

[array([[-0.31014077, -1.2396806 , -0.59347881, -0.43817284],
        [ 0.28143276, -0.20621966,  1.66945183, -1.07688513],
        [ 0.3002728 ,  0.50302378, -1.09557915, -1.52114107]]),
 array([[ 0.69714806, -0.19580128],
        [ 0.11989141,  0.76399539],
        [-0.33265382,  0.02295053],
        [ 0.0554339 ,  0.36275798]]),
 array([[1.40695393],
        [0.22088226]]),
 array([-0.77140026])]

In [204]:
z

array([[0.8539582 ],
       [0.87670801],
       [0.87000312],
       [0.85624991]])

In [170]:

e=d.dot(w[i].T)+b[i]
d=e*sigmoid(z_values[i],derivative=True)
delta.append(d)

ValueError: operands could not be broadcast together with shapes (3,) (4,4) 

In [171]:
for i in range(len(z_values),0,-1):
    print(i)

4
3
2
1


In [115]:
z_values[0]

array([[0.56989745, 0.44862702, 0.84150272, 0.25409593],
       [0.42308038, 0.22449159, 0.35583705, 0.39217643],
       [0.49282349, 0.19063332, 0.74573116, 0.18019041],
       [0.64145976, 0.57366107, 0.63965629, 0.06926556]])

In [102]:
w[2]

array([[1.40695393],
       [0.22088226]])

In [19]:
w

[array([[ 0.41765968,  0.89395769,  0.04735517, -0.60842552],
        [-0.26854813, -0.66630197, -0.34401183,  0.80705192],
        [ 2.14180538, -0.49561818,  0.52563742, -0.38964647]]),
 array([[-0.8169742 ,  1.01961544],
        [-0.34143633,  0.7512814 ],
        [-0.36225179, -1.12913125],
        [-0.34971048, -1.05272652]]),
 array([[-0.17180538],
        [ 0.57765806]]),
 array([0.07878845])]