In [1]:
import numpy as np

# Activation Functions

In [7]:
def sigmoid(z):
    return 1/(1+np.exp(-z))
def sigmoid_derivative(z):
    return sigmoid(z)*(1-sigmoid(z))

# Cost function

In [21]:
def cost(predicted,y_true):
    cos=[]
    for p,t in zip(predicted,y_true):
        cos.append((p-t)**2)
    cost=np.sum(cos)
    cost=cost/(2*len(y_true))
    return cost
            
        

In [24]:
def cost_derivate(predicted,y_true):
    cos=[]
    for p,t in zip(predicted,y_true):
        cos.append(p-t)
    return np.sum(cos)

# X and Y values

In [26]:
x=np.array([[0,1,0],[1,0,0],[1,1,0],[0,1,1]])
y=np.array([0,0,1,1])

# Weight and bias initialization

In [27]:
layers=[3,4,2,1]

In [188]:
def weight_bias_init(layers):
    w=[]
    b=[]
    for i in range(1,len(layers)):
        w1=np.random.rand(layers[i],layers[i-1]) * np.sqrt(1 / layers[i-1])
        w.append(w1)
        b.append(np.random.rand(layers[i]))
    return w,b

In [198]:
w,b=weight_bias_init(layers)
    

In [191]:
w[2].shape

(1, 2)

# Forward Probagation

In [178]:
def forward(x,w,b):
    a=x
    pre_activation=[]
    after_activation=[a]
    for ws,bs in zip(w,b):
        z=np.dot(ws,a.T)+bs
        a=sigmoid(z)
        pre_activation.append(z)
        after_activation.append(a)
    return a, pre_activation,after_activation
        
    

In [200]:
a=x

In [202]:

z=np.dot(w[1],a.T)+b[1]
a=sigmoid(z)
a.shape

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [187]:
w

[array([[0.23326271, 0.27570739, 0.1220697 ],
        [0.50889072, 0.48216016, 0.27786709],
        [0.16136894, 0.18414075, 0.44287364],
        [0.49578688, 0.11874253, 0.02931609]]),
 array([[0.35789023, 0.30896086, 0.18216074, 0.47789694],
        [0.32730058, 0.42360259, 0.16858405, 0.43264265]]),
 array([[0.69677832, 0.3495519 ]])]

In [180]:
pre_activation

[array([[1.14933291, 1.30445612, 0.38999561, 0.15191992],
        [1.10688824, 1.33118668, 0.3672238 , 0.52896427],
        [1.38259563, 1.81334683, 0.55136455, 0.6477068 ],
        [1.27140261, 1.58232321, 0.83286925, 0.18123602]]),
 array([[1.38213496, 1.72558326],
        [1.42335238, 1.76349232],
        [1.48269277, 1.82742185],
        [1.42495094, 1.77096621]]),
 array([[0.94099819],
        [0.9472258 ],
        [0.95630654],
        [0.94772551]])]

In [181]:
a, pre_activation,after_activation=forward(x,w,b)

ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

# Compute detla

In [147]:
delta_L= cost_derivate(y_true=y,predicted=a)*sigmoid_derivative(pre_activation[-1])
delta=[0]*(len(layers)-1)
delta[-1]=delta_L

In [148]:

for i in range(len(w)-2,-1,-1):
    d=np.dot(delta[i+1],w[i+1])*sigmoid_derivative(pre_activation[i])
    delta[i]=d

In [168]:
def compute_delta(y,a,w):
    delta_L= cost_derivate(y_true=y,predicted=a)*sigmoid_derivative(pre_activation[-1])
    delta=[0]*(len(layers)-1)
    delta[-1]=delta_L
    for i in range(len(w)-2,-1,-1):
        d=np.dot(delta[i+1],w[i+1])*sigmoid_derivative(pre_activation[i])
        delta[i]=d
    return delta
    

In [169]:
delta=compute_delta(y,a,w)

In [170]:
delta

[array([[0.00178096, 0.00160185, 0.00119813, 0.0032264 ],
        [0.00176951, 0.00153332, 0.00116985, 0.00294423],
        [0.00145532, 0.00107026, 0.00107475, 0.00272558],
        [0.00161716, 0.00130814, 0.0010196 , 0.00312193]]),
 array([[0.01992319, 0.00799503],
        [0.01937918, 0.00776363],
        [0.01860318, 0.0073869 ],
        [0.01935596, 0.00772094]]),
 array([[0.17826313],
        [0.17777549],
        [0.17706188],
        [0.1777363 ]])]

# Back probagation

In [171]:
dw=[]
db=[]
delta=[0]+delta

In [173]:
np.dot(delta[i],after_activation[i-1])

ValueError: shapes (4,2) and (4,4) not aligned: 2 (dim 1) != 4 (dim 0)

In [174]:
for i in range(1, len(layers)):
    dw1=np.dot(delta[i],after_activation[i-1])
    db1=delta[i]
    dw.append(dw1)
    db.append(np.expand_dims(db1.mean(axis=1), 1))

ValueError: shapes (4,2) and (4,4) not aligned: 2 (dim 1) != 4 (dim 0)

In [175]:
def back_prob(delta,after_activation):
    dw=[]
    db=[]
    delta=[0]+delta
    for i in range(1, len(layers)):
        dw1=np.dot(delta[i],after_activation[i-1])
        db1=delta[i]
        dw.append(dw1)
        db.append(np.expand_dims(db1.mean(axis=1), 1))
    return dw,db

# Training

In [166]:
dw,db=back_prob(delta,after_activation)

ValueError: shapes (4,2) and (4,4) not aligned: 2 (dim 1) != 4 (dim 0)

In [95]:
dw

[array([[0.00935392, 0.00975342, 0.01079831, 0.01108891],
        [0.00887195, 0.00905792, 0.0101578 , 0.01046417],
        [0.00638895, 0.00662917, 0.00735589, 0.00755628],
        [0.00560458, 0.0058701 , 0.00647415, 0.00663628]]),
 array([[0.03421384, 0.03442721, 0.03519537, 0.03539865],
        [0.03338513, 0.03359329, 0.03434306, 0.03454136],
        [0.03036954, 0.03055903, 0.0312405 , 0.03142103],
        [0.02955498, 0.02973933, 0.03040276, 0.03057839]]),
 array([[0.14818533, 0.14843277, 0.14931317, 0.14954483],
        [0.14761911, 0.1478656 , 0.14874264, 0.14897341],
        [0.14558242, 0.14582551, 0.14669044, 0.14691803],
        [0.14504081, 0.14528299, 0.14614471, 0.14637145]])]

In [93]:
epoch=10
lr=0.0001

In [ ]:
for _ in range(epoch):
    a, pre_activation,after_activation=forward(x,w,b)
    delta=compute_delta(y,a,w)
    dw,db=back_prob(delta,after_activation)
    
    

In [102]:
w[0]-=dw[0]*0.1

ValueError: operands could not be broadcast together with shapes (4,3) (4,4) (4,3) 

In [100]:
dw

[array([[0.00935392, 0.00975342, 0.01079831, 0.01108891],
        [0.00887195, 0.00905792, 0.0101578 , 0.01046417],
        [0.00638895, 0.00662917, 0.00735589, 0.00755628],
        [0.00560458, 0.0058701 , 0.00647415, 0.00663628]]),
 array([[0.03421384, 0.03442721, 0.03519537, 0.03539865],
        [0.03338513, 0.03359329, 0.03434306, 0.03454136],
        [0.03036954, 0.03055903, 0.0312405 , 0.03142103],
        [0.02955498, 0.02973933, 0.03040276, 0.03057839]]),
 array([[0.14818533, 0.14843277, 0.14931317, 0.14954483],
        [0.14761911, 0.1478656 , 0.14874264, 0.14897341],
        [0.14558242, 0.14582551, 0.14669044, 0.14691803],
        [0.14504081, 0.14528299, 0.14614471, 0.14637145]])]